name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set Node.js Version
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install & Build
        run: |
          npm install
          npm run build
        env:
          CI: true
