name: Deploy & Release

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        if: github.event.pull_request.merged
        with:
          ref: master
      - name: Set Node.js Version
        uses: actions/setup-node@v1
        if: github.event.pull_request.merged
        with:
          node-version: "10.x"
      - name: Install & Deploy
        if: github.event.pull_request.merged
        run: |
          npm install
          npm run deploy
        env:
          CI: true

  release:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
