name: Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Checkout
        if: github.event.pull_request.merged
        with:
          ref: master
      - name: Set Node.js Version
        if: github.event.pull_request.merged
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install & Deploy
        if: github.event.pull_request.merged
        run: |
          npm install
          npm run deploy
        env:
          CI: true
